message("\n")
if(PROJECT_IS_TOP_LEVEL)
  message("Configure summary")
  message("=================")
else()
  message("minisketch configure summary")
  message("============================")
endif()
message("Build details:")
if(HAVE_CLMUL)
  set(_clmul_status "Enabled")
else()
  set(_clmul_status "Disabled")
endif()
message(" clmul fields ......................... ${_clmul_status}")
unset(_clmul_status)
if(HAVE_CLZ)
  set(_clz_status "Enabled")
else()
  set(_clz_status "Disabled")
endif()
message(" clz builtins ......................... ${_clz_status}")
unset(_clz_status)
message("Optional binaries:")
message("  benchmark ........................... ${MINISKETCH_BUILD_BENCHMARK}")
message("  tests ............................... ${MINISKETCH_BUILD_TESTS}")
message("")
if(CMAKE_CROSSCOMPILING)
  set(_cross_status "TRUE, for ${CMAKE_SYSTEM_NAME}, ${CMAKE_SYSTEM_PROCESSOR}")
else()
  set(_cross_status "FALSE")
endif()
message("Cross compiling ....................... ${_cross_status}")
unset(_cross_status)
message("C++ compiler .......................... ${CMAKE_CXX_COMPILER_ID} ${CMAKE_CXX_COMPILER_VERSION}, ${CMAKE_CXX_COMPILER}")

get_directory_property(compile_options COMPILE_OPTIONS)
string(REPLACE ";" " " compile_options "${compile_options}")
macro(print_flags_per_config config indent dots)
  string(TOUPPER "${config}" config_uppercase)
  string(STRIP "${CMAKE_CXX_COMPILER_ARG1} ${CMAKE_CXX_FLAGS}" combined_cxx_flags)
  string(STRIP "${combined_cxx_flags} ${CMAKE_CXX_FLAGS_${config_uppercase}}" combined_cxx_flags)
  string(STRIP "${combined_cxx_flags} ${CMAKE_CXX${CMAKE_CXX_STANDARD}_STANDARD_COMPILE_OPTION}" combined_cxx_flags)
  if(CMAKE_POSITION_INDEPENDENT_CODE)
    string(JOIN " " combined_cxx_flags ${combined_cxx_flags} ${CMAKE_CXX_COMPILE_OPTIONS_PIC})
  endif()
  if(CMAKE_CXX_COMPILE_OPTIONS_VISIBILITY AND CMAKE_CXX_VISIBILITY_PRESET)
    string(JOIN " " combined_cxx_flags ${combined_cxx_flags} ${CMAKE_CXX_COMPILE_OPTIONS_VISIBILITY}${CMAKE_CXX_VISIBILITY_PRESET})
  endif()
  string(STRIP "${combined_cxx_flags} ${compile_options}" combined_cxx_flags)
  message("${indent}" "C++ compiler flags ..................${dots} ${combined_cxx_flags}")
endmacro()

get_property(is_multi_config GLOBAL PROPERTY GENERATOR_IS_MULTI_CONFIG)
if(is_multi_config)
  list(JOIN CMAKE_CONFIGURATION_TYPES ", " configs)
  message("Available build configurations ........ ${configs}")
  if(CMAKE_GENERATOR MATCHES "Visual Studio")
    set(default_config "Debug")
  else()
    list(GET CMAKE_CONFIGURATION_TYPES 0 default_config)
  endif()
  message("Default build configuration ........... ${default_config}")
  foreach(config IN LISTS CMAKE_CONFIGURATION_TYPES)
    message("'${config}' build configuration:")
    print_flags_per_config("${config}" "  " "")
  endforeach()
else()
  message("CMAKE_BUILD_TYPE ...................... ${CMAKE_BUILD_TYPE}")
  print_flags_per_config("${CMAKE_BUILD_TYPE}" "" "..")
endif()

message([=[

NOTE: The summary above may not exactly match the final applied build flags
      if any additional CMAKE_* or environment variables have been modified.
      To see the exact flags applied, build with the --verbose option.
]=])

if(have_disabled_fields)
message("")
message(WARNING
  "Only compiling in support for field sizes: ${MINISKETCH_FIELDS}\n"
  "This means the library will lack support for other field sizes entirely.\n"
)
endif()
