name: CI
on:
  pull_request:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

concurrency:
  group: ${{ github.event_name != 'pull_request' && github.run_id || github.ref }}
  cancel-in-progress: true

env:
  BUILD: 'check'
  HOST:
  MAKEFLAGS: '-j4'
  BENCH: 'yes'
  TESTRUNS:
  EXEC_CMD:
  ENABLE_FIELDS:
  # Disable Docker build summary generation.
  # See https://github.com/docker/build-push-action/blob/master/README.md#environment-variables.
  DOCKER_BUILD_SUMMARY: false

jobs:
  docker_cache:
    name: "Build ${{ matrix.arch }} Docker image"
    runs-on: ${{ matrix.runner }}
    outputs:
      cache_scope: ${{ steps.cache_timestamp.outputs.period }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: x64
            runner: ubuntu-26.04
          - arch: arm64
            runner: ubuntu-26.04-arm
    steps:
      - name: Get cache validity period
        id: cache_timestamp
        run: echo "period=$((10#$(date +%V) / 4))" >> "$GITHUB_OUTPUT"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
        with:
          # See: https://github.com/moby/buildkit/issues/3969.
          driver-opts: |
            network=host
      - name: Build container
        uses: docker/build-push-action@v7
        with:
          file: ./ci/linux-debian.Dockerfile
          cache-from: type=gha,scope=${{ runner.arch }}-${{ steps.cache_timestamp.outputs.period }}
          cache-to: type=gha,scope=${{ runner.arch }}-${{ steps.cache_timestamp.outputs.period }},mode=min

  x86_64-debian:
    name: "x86_64: Linux (Debian stable)"
    runs-on: ubuntu-latest
    needs: docker_cache
    strategy:
      fail-fast: false
      matrix:
        configuration:
          - env_vars:
              ENABLE_FIELDS: '11,64,37'
          - env_vars:
              BUILD: 'distcheck'
          - env_vars:
              EXEC_CMD: 'valgrind --error-exitcode=42'
              TESTRUNS: 1
              BUILD:
          - env_vars:
              CXXFLAGS: '-fsanitize=undefined -fno-omit-frame-pointer'
              LDFLAGS: '-fsanitize=undefined -fno-omit-frame-pointer'
              UBSAN_OPTIONS: 'print_stacktrace=1:halt_on_error=1'
              BENCH: 'no'
        cxx:
          - 'g++'
          - 'clang++ -gdwarf-4'
    env:
      CXX: ${{ matrix.cxx }}
    steps:
      - &CHECKOUT
        name: Checkout
        uses: actions/checkout@v7
      - &CI_SCRIPT_IN_DOCKER
        name: CI script
        env: ${{ matrix.configuration.env_vars }}
        uses: ./.github/actions/run-in-docker-action
        with:
          dockerfile: ./ci/linux-debian.Dockerfile
          scope: ${{ runner.arch }}-${{ needs.docker_cache.outputs.cache_scope }}
          command: ./ci/ci.sh
      - &PRINT_LOGS
        name: Print logs
        uses: ./.github/actions/print-logs
        if: ${{ !cancelled() }}

  i686_debian:
    name: "i686: Linux (Debian stable)"
    runs-on: ubuntu-latest
    needs: docker_cache
    strategy:
      fail-fast: false
      matrix:
        configuration:
          - env_vars:
              ENABLE_FIELDS: '7,32,58'
          - env_vars:
              BUILD: 'distcheck'
          - env_vars:
              EXEC_CMD: 'valgrind --error-exitcode=42'
              TESTRUNS: 1
              BUILD:
        compiler:
          - cxx: 'i686-linux-gnu-g++'
          - cxx: 'clang++ --target=i686-linux-gnu -gdwarf-4'
            cxxflags: '-g -O2 -isystem /usr/i686-linux-gnu/include -isystem /usr/i686-linux-gnu/include/c++/10/i686-linux-gnu'
    env:
      HOST: 'i686-linux-gnu'
      CXX: ${{ matrix.cxx }}
      CXXFLAGS: ${{ matrix.cxxflags }}
    steps:
      - *CHECKOUT
      - *CI_SCRIPT_IN_DOCKER
      - *PRINT_LOGS

  arm64-macos-native:
    name: "ARM64: macOS Sonoma"
    # See: https://github.com/actions/runner-images#available-images.
    runs-on: macos-14
    env:
      # GHA gives us a fixed number of 3 virtual CPUs.
      # See: https://docs.github.com/en/actions/reference/runners/github-hosted-runners.
      MAKEFLAGS: -j4
    strategy:
      fail-fast: false
      matrix:
        env_vars:
          - CXX: 'g++-11'
            ENABLE_FIELDS: 28
          - CXX: 'g++-11'
            BUILD: 'distcheck'
          - CXX: 'clang++'
            ENABLE_FIELDS: 28
          - CXX: 'clang++'
            BUILD: distcheck
          - CXX: 'clang++'
            CXXFLAGS: '-fsanitize=undefined -fno-omit-frame-pointer'
            LDFLAGS: '-fsanitize=undefined -fno-omit-frame-pointer'
            UBSAN_OPTIONS: 'print_stacktrace=1:halt_on_error=1'
            BENCH: 'no'
    steps:
      - *CHECKOUT
      - name: Install Homebrew packages
        run: |
          brew update
          brew install automake libtool gcc@11
      - name: CI script
        env: ${{ matrix.env_vars }}
        run: ./ci/ci.sh
      - *PRINT_LOGS

  s390x_debian:
    name: "s390x (big-endian): Linux (Debian stable, QEMU)"
    runs-on: ubuntu-latest
    needs: docker_cache
    strategy:
      matrix:
        configuration:
          - env_vars: {}
    env:
      EXEC_CMD: 'qemu-s390x'
      HOST: 's390x-linux-gnu'
      BUILD:
    steps:
      - *CHECKOUT
      - *CI_SCRIPT_IN_DOCKER
      - *PRINT_LOGS

  mingw_debian:
    name: "x86_64-w64-mingw32: Linux (Debian stable, Wine)"
    runs-on: ubuntu-latest
    needs: docker_cache
    strategy:
      matrix:
        configuration:
          - env_vars: {}
    env:
      EXEC_CMD: 'wine'
      EXEC_EXT: '.exe'
      HOST: 'x86_64-w64-mingw32'
      BUILD:
    steps:
      - *CHECKOUT
      - *CI_SCRIPT_IN_DOCKER
      - *PRINT_LOGS

  windows-native:
    name: ${{ matrix.configuration.job_name }}
    # See: https://github.com/actions/runner-images#available-images.
    runs-on: windows-2025
    strategy:
      fail-fast: false
      matrix:
        configuration:
          - job_name: 'x64 (MSVC): Windows (VS 2022)'
            build_configuration: 'Release'
          - job_name: 'x64 (MSVC): Windows (VS 2022, fields=32)'
            cmake_options: '-DMINISKETCH_FIELDS=32'
            build_configuration: 'Release'
          - job_name: 'x64 (MSVC): Windows (VS 2022, debug)'
            build_configuration: 'Debug'
            # TODO: Resolve the issue and re-enable benchmark.
            # See: https://github.com/bitcoin-core/minisketch/pull/96.
            skip_benchmark: true
          - job_name: 'x64 (MSVC): Windows (VS 2022, shared)'
            cmake_options: '-DBUILD_SHARED_LIBS=ON'
            build_configuration: 'Release'
          - job_name: 'x64 (clang-cl): Windows (VS 2022)'
            cmake_options: '-T ClangCL'
            build_configuration: 'Release'
            # TODO: Resolve the issue and re-enable benchmark.
            # See: https://github.com/bitcoin-core/minisketch/pull/96.
            skip_benchmark: true
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Generate buildsystem
        env:
          CXXFLAGS: '/WX'
        run: cmake -B build -DMINISKETCH_BUILD_BENCHMARK=ON ${{ matrix.configuration.cmake_options }}
      - name: Build
        run: cmake --build build --config ${{ matrix.configuration.build_configuration }}
      - name: Binaries info
        shell: bash
        run: |
          cd build/bin/${{ matrix.configuration.build_configuration }}
          file * | grep "\.exe\|\.dll"
      - name: Check
        working-directory: build
        run: ctest --output-on-failure -j $env:NUMBER_OF_PROCESSORS -C ${{ matrix.configuration.build_configuration }}
      - name: Benchmark
        if: ${{ ! matrix.configuration.skip_benchmark }}
        working-directory: build
        run: bin\${{ matrix.configuration.build_configuration }}\bench.exe
