name: CI
on:
  pull_request:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

concurrency:
  group: ${{ github.event_name != 'pull_request' && github.run_id || github.ref }}
  cancel-in-progress: true

jobs:
  windows-native:
    name: ${{ matrix.configuration.job_name }}
    # See: https://github.com/actions/runner-images#available-images.
    runs-on: windows-2025

    strategy:
      fail-fast: false
      matrix:
        configuration:
          - job_name: 'x64 (MSVC): Windows (VS 2022)'
            build_configuration: 'Release'
          - job_name: 'x64 (MSVC): Windows (VS 2022, Debug)'
            build_configuration: 'Debug'
          - job_name: 'x64 (MSVC): Windows (VS 2022, RelWithDebInfo)'
            build_configuration: 'RelWithDebInfo'
          - job_name: 'x64 (MSVC): Windows (VS 2022, shared)'
            cmake_options: '-DBUILD_SHARED_LIBS=ON'
            build_configuration: 'Release'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate buildsystem
        run: cmake -B build -DMINISKETCH_BUILD_BENCHMARK=ON ${{ matrix.configuration.cmake_options }}

      - name: Build
        run: cmake --build build --config ${{ matrix.configuration.build_configuration }}

      - name: Binaries info
        shell: bash
        run: |
          cd build/bin/${{ matrix.configuration.build_configuration }}
          file * || true

      - name: Check
        working-directory: build
        shell: bash
        run: |
          ctest --output-on-failure -j $NUMBER_OF_PROCESSORS -C ${{ matrix.configuration.build_configuration }}
          bin/${{ matrix.configuration.build_configuration }}/bench.exe
